server:
  port: 9000
spring:
  kafka:
    consumer:
      # replace localhost with your kafka broker IP
      bootstrap-servers: localhost:9092
      group-id: myconsumergroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      # replace localhost with your kafka broker IP
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer